In [8]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [9]:
x.requires_grad

False

In [10]:
x.requires_grad_(True)
x.requires_grad, x

(True, tensor([0., 1., 2., 3.], requires_grad=True))

In [11]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4 * x

tensor([True, True, True, True])

In [15]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
# 在我们的例子中，我们只想求偏导数的和，所以传递一个1的梯度是合适的
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [17]:
# 分离计算
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [18]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [19]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [20]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [27]:
a.grad == d / a, a.grad, d, a

(tensor(True),
 tensor(1024.),
 tensor(1196.0417, grad_fn=<MulBackward0>),
 tensor(1.1680, requires_grad=True))